# Generated by Django 3.2.4 on 2021-06-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('recipes', '0002_auto_20210606_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list_session', to='recipes.recipe')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
            options={
                'unique_together': {('session', 'recipe')},
            },
        ),
    ]
